//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicTheGathering_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expansion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expansion()
        {
            this.Kaart = new HashSet<Kaart>();
        }
    
        public int ID { get; set; }
        public string Naam { get; set; }
        public string Symbool { get; set; }
        public Nullable<int> AantalKaarten { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kaart> Kaart { get; set; }
    }
}
