//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicTheGathering_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MagicTheGatheringEntities : DbContext
    {
        public MagicTheGatheringEntities()
            : base("name=MagicTheGatheringEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artist> Artist { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Deck> Deck { get; set; }
        public virtual DbSet<Expansion> Expansion { get; set; }
        public virtual DbSet<Kaart> Kaart { get; set; }
        public virtual DbSet<Rarity> Rarity { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type> Type { get; set; }
    }
}
